[package]
name = "bakkesmod"
version = "0.1.0"
authors = ["Arator"]
edition = "2018"

[dependencies]
bakkesmod-macros = { path = "crates/bakkesmod-macros"}

[lib]
name = "bakkesmod"

[workspace]
members = [
    "crates/bakkesmod-macros",
    "examples/rustplugin",
    "examples/tinyplugin",
]