[package]
name = "rustplugin"
version = "0.1.0"
authors = ["Arator"]
edition = "2018"

[dependencies]
bakkesmod = { path = "../../" }
bakkesmod-macros = { path = "../../crates/bakkesmod-macros" }

[lib]
name = "rustplugin"
crate_type = ["cdylib"]